input <- Sys.getenv("MYPATH")
source("./species-indices/njot-index-stratified/WGTED-ARIM.R")
source("./species-indices/njot-index-stratified/LFD WGTED.R")
outdir <- file.path(Sys.getenv("FILEPATH"),"output/sasr")

#index <- WgtedAriM(input, "Jonah crab", outdir=outdir)
# index <- WgtedAriM(input, "Black drum", area="INM", cruise="Oct", outdir=outdir)
# index <- WgtedAriM(input, "Scup", outdir=outdir) #"INM", "AugOct"
#index <- WgtedAriM(input, myspp="Spot", area="INM", cruise="AugOct", outdir=outdir)
index <- WgtedAriM(input, "Spot", outdir=outdir)
# index <- WgtedAriM(input, "Summer flounder", outdir=outdir)
# index <- WgtedAriM(input, "Summer flounder", cruise="AprthruOct", outdir=outdir)
# index <- WgtedAriM(input, "Tautog", outdir=outdir)
# index <- WgtedAriM(input, "Weakfish", cruise="AugOct", outdir=outdir)
## index <- WgtedAriM(input, "Lobster - F (GE53mm)")
## index <- WgtedAriM(input, "Lobster - M (GE53mm)")
# WgtedAriM(mypath=input, myspp="Atl croaker", cruise="AugOct", outdir=outdir)
# lf <- LFD(input, "Summer flounder", cruise="AprthruOct", outdir=outdir)
# index <- WgtedAriM(input, myspp="Lobster - F (GE53mm)", outdir=outdir)
# index <- WgtedAriM(input, "Lobster - F (GE53mm)", cruise="Spring", outdir=outdir)
# index <- WgtedAriM(input, "Lobster - F (GE53mm)", cruise="Oct", outdir=outdir)
# lf <- LFD(input, myspp="Lobster - F (GE53mm)", cruise="Spring", outdir=outdir)
# lf <- LFD(input, "Lobster - F (GE53mm)", cruise="Oct", outdir=outdir)

# index <- WgtedAriM(input, "Lobster - M (GE53mm)", outdir=outdir)
# index <- WgtedAriM(input, "Lobster - M (GE53mm)", cruise="Spring", outdir=outdir)
# index <- WgtedAriM(input, "Lobster - M (GE53mm)", cruise="Oct", outdir=outdir)
# lf <- LFD(input, "Lobster - M (GE53mm)", cruise="Spring", outdir=outdir)
# lf <- LFD(input, "Lobster - M (GE53mm)", cruise="Oct", outdir=outdir)

# index <- WgtedAriM(input, "Striped bass", cruise="Apr", outdir=outdir)
#lf <- LFD(input, "Striped bass", cruise = "Apr", outdir = outdir, totlenin=T)
lf <- LFD(input, "Spot", outdir = outdir)
